services:

  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - vpn-net

  pritunl:
    image: jippi/pritunl
    container_name: pritunl
    restart: always
    depends_on:
      - mongodb
    ports:
      - "80:80"
      - "443:443"
      - "1194:1194/udp"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pritunl
    volumes:
      - pritunl_data:/var/lib/pritunl
    networks:
      - vpn-net

networks:
  vpn-net:

volumes:
  mongo_data:
  pritunl_data:
